services:
  web:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./ui/src:/app/src
    command: "npm run dev"
    networks:
      - dev
      - default
  web-prod:
    build:
      context: ./ui
      dockerfile: Dockerfile.prod
    ports:
      - "8080:8080"
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - dev
      - default
    # network_mode: "host"
    command: uv run fastapi run main.py
    environment:
      DB_HOST: "db"
  db:
    image: postgres:16.6
    restart: always
    ports:
      - "5432:5432"
    networks:
      - dev
      - default
    environment:
      POSTGRES_USER: localuser
      POSTGRES_PASSWORD: localpass
      POSTGRES_DB: show-voter
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata:

networks:
  dev:
