"""add poll show fk

Revision ID: a49ac3567835
Revises: ebddcb3942dd
Create Date: 2025-08-01 16:59:33.991718

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a49ac3567835"
down_revision: Union[str, Sequence[str], None] = "ebddcb3942dd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("poll", sa.Column("show_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "poll", "show", ["show_id"], ["id"])
    op.add_column("user", sa.Column("date_created", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "date_created")
    op.drop_constraint(None, "poll", type_="foreignkey")
    op.drop_column("poll", "show_id")
    # ### end Alembic commands ###
