"""add model for colors

Revision ID: 77d35d331348
Revises: 93c008b9ed85
Create Date: 2025-10-23 16:54:08.095816

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "77d35d331348"
down_revision: Union[str, Sequence[str], None] = "93c008b9ed85"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "color",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("hex", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_color_id"), "color", ["id"], unique=False)
    op.add_column("poll_option", sa.Column("color_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "poll_option", "color", ["color_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "poll_option", type_="foreignkey")
    op.drop_column("poll_option", "color_id")
    op.drop_index(op.f("ix_color_id"), table_name="color")
    op.drop_table("color")
    # ### end Alembic commands ###
