"""add poll restrictions

Revision ID: 93c008b9ed85
Revises: aafae2c9142c
Create Date: 2025-10-21 20:41:57.775903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93c008b9ed85'
down_revision: Union[str, Sequence[str], None] = 'aafae2c9142c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poll', sa.Column('is_accepting_votes', sa.Boolean(), nullable=True))
    op.add_column('poll_vote', sa.Column('user_ip', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('poll_vote', 'user_ip')
    op.drop_column('poll', 'is_accepting_votes')
    # ### end Alembic commands ###
