"""add active flags for polls and options

Revision ID: adccea39f34d
Revises: 8c15b7343cae
Create Date: 2025-10-02 21:05:40.579221

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "adccea39f34d"
down_revision: Union[str, Sequence[str], None] = "8c15b7343cae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("poll", sa.Column("is_active", sa.Boolean(), nullable=True))
    op.add_column("poll", sa.Column("is_display", sa.Boolean(), nullable=True))
    op.add_column("poll_option", sa.Column("is_active", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("poll_option", "is_active")
    op.drop_column("poll", "is_display")
    op.drop_column("poll", "is_active")
    # ### end Alembic commands ###
