FROM node:lts-alpine AS build

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx

WORKDIR /app
COPY --from=build /app/dist /app/dist
USER root
RUN cp -r /app/dist/* /usr/share/nginx/html
# COPY ./nginx/default.config /etc/nginx/conf.d/
USER nginx
EXPOSE 8080

